services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: search-docnum:latest
    command: python -m search_docnum
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./:/app
    init: true
    restart: "no"
