services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: search-docnum:latest
    command: python -m search_docnum
    environment:
      PYTHONUNBUFFERED: "1"
      APP_HOST: "0.0.0.0"
      APP_PORT: "${APP_PORT:-8000}"
      APP_RELOAD: "${APP_RELOAD:-0}"
    volumes:
      - ./:/app
    init: true
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped
